/* Criar o banco de dados */
IF EXISTS (SELECT 1 FROM sys.databases WHERE name ='Projeto_Estacio')
	BEGIN
		DROP DATABASE Projeto_Estacio;
	END
ELSE
	BEGIN
		CREATE DATABASE Projeto_Estacio;
	END
GO

/* Usar o banco criado */
USE Projeto_Estacio;
GO

/* Criação das tabelas */
CREATE TABLE dbo.JOGOS (
	ID_PRODUTO INT NOT NULL,
	PRECO NUMERIC(6,2) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	PUBLISHER VARCHAR(50) NOT NULL,
	GENERO VARCHAR(50) NOT NULL,
	DATA_LANCAMENTO DATETIME,
	CONSTRAINT PK_JOGOS_ID_PRODUTO PRIMARY KEY (ID_PRODUTO)
) ON [PRIMARY]
GO

CREATE TABLE dbo.TRANSACOES (
	ID INT IDENTITY (1,1),
	DATA_COMPRA DATETIME
	CONSTRAINT DF_TRANSACOES_DATA_COMPRA DEFAULT GETDATE(),
	VALOR_PAGO NUMERIC(6,2) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE SMALLINT,
	CONSTRAINT PK_TRANSACOES_ID PRIMARY KEY (ID),
	CONSTRAINT FK_TRANSACOES_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES JOGOS (ID_PRODUTO)
) ON [PRIMARY]
GO

/* Adição de valores randomicos na tabela JOGOS */
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (1,	100.00,		'STREET FIGHTER',		'PUBLISHER A',		'AÇÃO',			GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (2,	120.00,		'MARVEL VS CAPCOM',		'PUBLISHER B',		'AVENTURA',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (3,	90.00,		'TEKKEN',			'PUBLISHER C',		'COMÉDIA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (4,	80.00,		'AGE OF EMPIRES',		'PUBLISHER D',		'TERROR',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (5,	50.00,		'AVENGERS',			'PUBLISHER E',		'DRAMA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (6,	25.00,		'BATMAN',			'PUBLISHER F',		'INFANTIL',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (7,	30.00,		'LIGA DA JUSTICA',		'PUBLISHER A',		'AÇÃO',			GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (8,	100.00,		'HOMEM ARANHA',			'PUBLISHER B',		'AVENTURA',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (9,	48.00,		'HELLBOY',			'PUBLISHER C',		'COMÉDIA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (10,	12.00,		'ROBOCOP',			'PUBLISHER D',		'TERROR',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (11,	33.00,		'HULK',				'PUBLISHER E',		'DRAMA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (12,	80.00,		'THOR',				'PUBLISHER F',		'INFANTIL',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (13,	24.00,		'HOMEM ARANHA',			'PUBLISHER A',		'AÇÃO',			GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (14,	44.00,		'TURMA DA MONICA',		'PUBLISHER B',		'AVENTURA',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (15,	51.00,		'ANNABELLE',			'PUBLISHER C',		'COMÉDIA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (16,	79.00,		'DOMINO',			'PUBLISHER D',		'TERROR',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (17,	95.00,		'SUPERMAN',			'PUBLISHER E',		'DRAMA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (18,	23.00,		'MULHER MARAVILHA',		'PUBLISHER F',		'INFANTIL',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (19,	22.00,		'LANTERNA VERDE',		'PUBLISHER F',		'INFANTIL',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (20,	55.00,		'WOLVERINE',			'PUBLISHER E',		'DRAMA',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (21,	67.00,		'X-MEN',			'PUBLISHER D',		'TERROR',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (22,	89.00,		'GAVIÃO NEGRO',			'PUBLISHER C',		'COMÉDIA',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (23,	2.00,		'VIUVA NEGRA',			'PUBLISHER B',		'AVENTURA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (24,	5.00,		'GROOT',			'PUBLISHER A',		'AÇÃO',			GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (25,	105.00,		'PANTERA NEGRA',		'PUBLISHER A',		'AÇÃO',			GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (26,	22.00,		'VENOM',			'PUBLISHER B',		'AVENTURA',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (27,	13.00,		'CARNIFICINA',			'PUBLISHER C',		'COMÉDIA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (28,	11.00,		'DOUTOR ESTRANHO',		'PUBLISHER D',		'TERROR',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (29,	71.00,		'CAPITÃ MARVEL',		'PUBLISHER E',		'DRAMA',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (30,	33.00,		'NICK FURY',			'PUBLISHER F',		'INFANTIL',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (31,	89.00,		'DOUTOR DESTINO',		'PUBLISHER G',		'FICÇÃO',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (32,	44.00,		'QUARTETO FANTÁSTICO',		'PUBLISHER G',		'FICÇÃO',		GETDATE()-501);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (33,	11.00,		'SURFISTA PRATEADO',		'PUBLISHER G',		'FICÇÃO',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (34,	93.00,		'GALACTUS',			'PUBLISHER G',		'FICÇÃO',		GETDATE()-500);
INSERT INTO JOGOS (ID_PRODUTO, PRECO, NOME, PUBLISHER, GENERO, DATA_LANCAMENTO ) VALUES (35,	56.00,		'TOCHA HUMANO',			'PUBLISHER G',		'FICÇÃO',		GETDATE()-500);
GO

/* Adição de valores randomicos na tabela TRANSAÇÕES */
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	1	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	2	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	3	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	4	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	5	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	6	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	7	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	8	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	9	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	10	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	11	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	12	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	13	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	14	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	15	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	16	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	17	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	18	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	19	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	20	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	21	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	22	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	23	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	24	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	25	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	26	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	27	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	28	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	29	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	30	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	31	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	32	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	33	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	34	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	35	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	1	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	2	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	3	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	4	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	5	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	6	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	7	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	8	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	9	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	10	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	11	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	12	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	13	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	14	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	15	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	16	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	17	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	18	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	19	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	20	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	21	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	22	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	23	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	24	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	25	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	26	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	27	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	28	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	29	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	30	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	31	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	32	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	33	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	34	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	35	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	1	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	2	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	3	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	4	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	5	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	6	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	7	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	8	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	9	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	10	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	11	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	12	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	13	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	14	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	15	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	16	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	17	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	18	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	19	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	20	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	21	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	22	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	23	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	24	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	25	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	26	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	27	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	28	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	29	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	30	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	31	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	32	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	33	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	34	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	35	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	1	,	1	)
INSERT INTO TRANSACOES (DATA_COMPRA, VALOR_PAGO, ID_PRODUTO, QUANTIDADE) VALUES	(	GETDATE()	,	0	,	2	,	1	)
GO

/* Atualizando tabela de transações com alguns valores */
UPDATE TRANSACOES SET DATA_COMPRA = '20190101' 		WHERE ID = 	1
UPDATE TRANSACOES SET DATA_COMPRA = '20190101' 		WHERE ID = 	2
UPDATE TRANSACOES SET DATA_COMPRA = '20190101' 		WHERE ID = 	3
UPDATE TRANSACOES SET DATA_COMPRA = '20190601' 		WHERE ID = 	4
UPDATE TRANSACOES SET DATA_COMPRA = '20190601' 		WHERE ID = 	5
UPDATE TRANSACOES SET DATA_COMPRA = '20190601' 		WHERE ID = 	6
UPDATE TRANSACOES SET DATA_COMPRA = '20191201' 		WHERE ID = 	7
UPDATE TRANSACOES SET DATA_COMPRA = '20191201' 		WHERE ID = 	8
UPDATE TRANSACOES SET DATA_COMPRA = '20191201' 		WHERE ID = 	9
UPDATE TRANSACOES SET DATA_COMPRA = '20200101' 		WHERE ID = 	10
UPDATE TRANSACOES SET DATA_COMPRA = '20200101' 		WHERE ID = 	11
UPDATE TRANSACOES SET DATA_COMPRA = '20200101' 		WHERE ID = 	12
UPDATE TRANSACOES SET DATA_COMPRA = '20200601' 		WHERE ID = 	13
UPDATE TRANSACOES SET DATA_COMPRA = '20200601' 		WHERE ID = 	14
UPDATE TRANSACOES SET DATA_COMPRA = '20200601' 		WHERE ID = 	15
UPDATE TRANSACOES SET DATA_COMPRA = '20200601' 		WHERE ID = 	16
UPDATE TRANSACOES SET DATA_COMPRA = '20201201' 		WHERE ID = 	17
UPDATE TRANSACOES SET DATA_COMPRA = '20201201' 		WHERE ID = 	18
UPDATE TRANSACOES SET DATA_COMPRA = '20201201' 		WHERE ID = 	19
UPDATE TRANSACOES SET DATA_COMPRA = '20201224' 		WHERE ID = 	20
UPDATE TRANSACOES SET DATA_COMPRA = '20201224' 		WHERE ID = 	21
UPDATE TRANSACOES SET DATA_COMPRA = '20201224' 		WHERE ID = 	22
UPDATE TRANSACOES SET DATA_COMPRA = '20201230' 		WHERE ID = 	23
UPDATE TRANSACOES SET DATA_COMPRA = '20201230' 		WHERE ID = 	24
UPDATE TRANSACOES SET DATA_COMPRA = '20201230' 		WHERE ID = 	25
UPDATE TRANSACOES SET DATA_COMPRA = '20210102' 		WHERE ID = 	26
UPDATE TRANSACOES SET DATA_COMPRA = '20210102' 		WHERE ID = 	27
UPDATE TRANSACOES SET DATA_COMPRA = '20210102' 		WHERE ID = 	28
UPDATE TRANSACOES SET DATA_COMPRA = '20210102' 		WHERE ID = 	29
UPDATE TRANSACOES SET DATA_COMPRA = '20210701' 		WHERE ID = 	30
UPDATE TRANSACOES SET DATA_COMPRA = '20210712' 		WHERE ID = 	31
UPDATE TRANSACOES SET DATA_COMPRA = '20210722' 		WHERE ID = 	32
UPDATE TRANSACOES SET DATA_COMPRA = '20210725' 		WHERE ID = 	33
UPDATE TRANSACOES SET DATA_COMPRA = '20210801' 		WHERE ID = 	34
UPDATE TRANSACOES SET DATA_COMPRA = '20210801' 		WHERE ID = 	35
GO

/* Atualizando tabela de transações com alguns valores */
UPDATE TRANSACOES SET QUANTIDADE = 5 WHERE ID_PRODUTO BETWEEN 1 AND 5
UPDATE TRANSACOES SET QUANTIDADE = 4 WHERE ID_PRODUTO BETWEEN 6 AND 10
UPDATE TRANSACOES SET QUANTIDADE = 3 WHERE ID_PRODUTO BETWEEN 11 AND 15
UPDATE TRANSACOES SET QUANTIDADE = 2 WHERE ID_PRODUTO BETWEEN 16 AND 20
UPDATE TRANSACOES SET QUANTIDADE = 1 WHERE ID_PRODUTO BETWEEN 21 AND 25
UPDATE TRANSACOES SET QUANTIDADE = 6 WHERE ID_PRODUTO BETWEEN 26 AND 30
UPDATE TRANSACOES SET QUANTIDADE = 2 WHERE ID_PRODUTO BETWEEN 31 AND 35
GO

/* Atualizando tabela de transações com valores atualizados */
UPDATE A
SET VALOR_PAGO = QUANTIDADE * B.PRECO
FROM TRANSACOES AS A
INNER JOIN JOGOS AS B ON A.ID_PRODUTO = B.ID_PRODUTO
GO

/* Resolução das questões */
/* 
   Observação: Há outras formas de resolver os exercícios com tabelas temporárias, ctes etc.
   Fique livre para colocar e buscar novas soluções.
   Não se preocupe com questões de performance, pois não era o objetivo nesse momento.
 */

-- 1.	Apresente a instrução para mostrar os campos ID e DataCompra das Transações ordenados por DataCompra.
SELECT ID, DATA_COMPRA FROM TRANSACOES ORDER BY DATA_COMPRA
GO

--2.	Apresente as instruções para mostrar Produto e DataCompra das Transações ordenadas por DataCompra em ordem crescente.
SELECT A.NOME, B.DATA_COMPRA
FROM JOGOS AS A
INNER JOIN TRANSACOES AS B ON A.ID_PRODUTO = B.ID_PRODUTO
ORDER BY B.DATA_COMPRA
GO

--3.	Mostrar o total gasto nas Transações.
SELECT SUM(VALOR_PAGO) AS TOTAL_VALOR_PAGO
FROM TRANSACOES
GO

--4.	Mostre o Nome dos jogos e o Gênero de todos os Jogos que tiveram Transações
SELECT A.NOME, A.GENERO
FROM JOGOS AS A
INNER JOIN TRANSACOES AS B ON A.ID_PRODUTO = B.ID_PRODUTO
GO

--5.	Mostre os Produtos e ID_do_produto de todos os jogos da Publisher A
SELECT ID_PRODUTO, NOME
FROM JOGOS
WHERE PUBLISHER = 'PUBLISHER A'
GO

--6.	Mostre os Jogos com Preço acima da média da loja pela Publisher chamada de "Publisher A".
SELECT NOME, PRECO
FROM JOGOS
WHERE PRECO > (	SELECT SUM(VALOR_PAGO)/SUM(QUANTIDADE) AS MEDIA
		FROM TRANSACOES AS A
		WHERE ID_PRODUTO IN ( SELECT ID_PRODUTO FROM JOGOS WHERE PUBLISHER = 'PUBLISHER A')
		)
GO

--7.	Mostre as top 10 Publishers com a maior receita no mês passado.
SELECT TOP 10 SUM(VALOR_PAGO) AS VALOR_PAGO, B.PUBLISHER
FROM TRANSACOES AS A
INNER JOIN JOGOS AS B ON A.ID_PRODUTO = B.ID_PRODUTO
WHERE A.DATA_COMPRA >= CAST(DATEADD(MM,-1,DATEADD(DD,-DAY(GETDATE())+1,GETDATE())) AS DATE) AND DATA_COMPRA < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)
GROUP BY B.PUBLISHER
ORDER BY VALOR_PAGO DESC
GO

--8.	Mostre o Preço médio de Jogos transacionado agrupado por Gênero.
SELECT 	SUM(VALOR_PAGO) / SUM(QUANTIDADE) AS MEDIA_PRECO_JOGO_POR_GENERO,
	A.GENERO
FROM JOGOS AS A 
INNER JOIN TRANSACOES AS B ON A.ID_PRODUTO = B.ID_PRODUTO
GROUP BY A.GENERO
GO

--9.	Mostre o Nome dos top 10 Jogos com maior receita no último mês e que não são das 3 Publishers que mais venderam no mês passado.
SELECT DISTINCT TOP 10 A.NOME, A.PUBLISHER
FROM JOGOS AS A
INNER JOIN TRANSACOES AS B ON A.ID_PRODUTO = B.ID_PRODUTO
INNER JOIN (	SELECT SUM(VALOR_PAGO) AS VALOR_PAGO, B.PUBLISHER, ROW_NUMBER() OVER (ORDER BY SUM(VALOR_PAGO) DESC, B.PUBLISHER) AS CLASSIFICACAO
		FROM TRANSACOES AS A
		INNER JOIN JOGOS AS B ON A.ID_PRODUTO = B.ID_PRODUTO
		WHERE  A.DATA_COMPRA >= CAST(DATEADD(MM,-1,DATEADD(DD,-DAY(GETDATE())+1,GETDATE())) AS DATE) AND A.DATA_COMPRA < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)
		GROUP BY B.PUBLISHER
) AS C ON A.PUBLISHER = C.PUBLISHER AND C.CLASSIFICACAO > 3
WHERE B.DATA_COMPRA >= CAST(DATEADD(MM,-1,DATEADD(DD,-DAY(GETDATE())+1,GETDATE())) AS DATE) AND B.DATA_COMPRA < DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)
GO

--10.	Mostre os Top 5 Gêneros que mais venderam com Jogos lançados em 2019 dentre as Publishers que possuem média de receita superior à média de receita total dentro da loja.
SELECT TOP 5 B.GENERO
FROM TRANSACOES AS A
INNER JOIN JOGOS AS B ON A.ID_PRODUTO = B.ID_PRODUTO
WHERE DATA_LANCAMENTO BETWEEN '20190101' AND '20191231 23:59:59.997'
GROUP BY B.GENERO
HAVING (SUM(VALOR_PAGO)/SUM(QUANTIDADE)) > (SELECT SUM(VALOR_PAGO)/SUM(QUANTIDADE) FROM TRANSACOES)
GO
